### ISSUE TITLE
Add possibility to run tests in parallel

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#11]
User should be able to run multiple tests in parallel, by specifying `--parallel [number]`, where [number] indicates max amount of tests that can run concurrently. In that case, each test must accept its own instance of webdriver.

**Comment by rdpanek** [comment]
maybe in next milestone, because it's very heavy topic

**Comment by jaroslav-kubicek** [comment]
Ok, that's true.
