### ISSUE TITLE
Add possibility to run tests in loop

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#12]
User should have opportunity to run tests in loop with option to specify what percentage of failed tests is considered as a failure. Name of the first option should be `--loop`, let's discuss the name for second one.

**Comment by rdpanek** [comment]
This isn't good idea and it's duplicate topic with https://github.com/test-stack/webdriver/issues/13

**Comment by jaroslav-kubicek** [comment]
No it's not duplicate, and why is it bad idea?

**Comment by jaroslav-kubicek** [comment]
Just to clarify: for example `--loop 10 --success 70` will run specified test 10x and it will be marked as "success" if at least 70 % runs succeed. On the other hand, in #13 , it will run test until it succeed, so it's possible that test will run only once.
