### ISSUE TITLE
Add possibility to run tests until it passed successfully

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#13]
Let's add another option, probably `--retry [number]`, where user can run specified tests until it ends with success or max number of attempts is reached, specified by [number].

**Comment by rdpanek** [comment]
This would not do, and mainly it does not apply any methodology.
- retest / confirmation test is depend on result of defect management
- generate some load is in role on tools e.g. Jmeter, in JS isn't good idea

**Comment by rdpanek** [comment]
close this issue, ok?
