### ISSUE TITLE
User should be able to pass file as capability option.

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#14]
The one of the ways how to enable users custom capability settings is via file. Currently only predefined name of capability can be used as cli option. This should be definitely changed and specifying file could be first alternative.

**Comment by rdpanek** [comment]
I agree

**Comment by rdpanek** [comment]
you can place example / your idea? because:
- there should be exist one functional and example global capabilitie file ( place to webdriver )
- then should by exist available custom capability and choice via CLI

**Comment by rdpanek** [comment]
done via `-c` options, more information in README
