### ISSUE TITLE
Name it properly!

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#15]
test-stack/webdriver is just boring and especially "webdriver" doesn't say anything about the fact, that this will be whole new environment, not just some another _webdriver_ for selenium.

**Comment by rdpanek** [comment]
I vote "Harrnes" because: https://en.wikipedia.org/wiki/Test_harness by ISTQB is test framework => in czech language `postroj` and in english is't `harness`

**Comment by jaroslav-kubicek** [comment]
:+1: for "harness", let's change it!

**Comment by rdpanek** [comment]
done
