### ISSUE TITLE
Add .editorconfig to unify code style across various editors

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#6]
Without .editorconfig, some editors tend to unwanted behavior. For example, sublime text doesn't insert new line at the end of file. Settings in .editorconfig ensure that unified code style is applied in all cases.

**Comment by rdpanek** [comment]
let's go ;-)

You can look at https://github.com/steida/daniel.steigerwald.cz/blob/master/.editorconfig what do you think?

Or http://editorconfig.org/

**Comment by jaroslav-kubicek** [comment]
cbd0708b99fdd7c52e1b758d8442597c257d1840 looks fine, let's merge it.

**Comment by rdpanek** [comment]
Merged to develop
