### ISSUE TITLE
Use mocha programmatically

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#7]
Let's stop executing tests by calling mocha executable via child process. Using mocha programmatically, see help on  [mocha wiki](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically), we'll gain much more power over what is't actually happening under the hood. With this, we will be able to:
- avoid managing subprocess on potentially malformed platform like windows 
- prepare custom reports
- report failures and test results in real time
- customize global context
- make screenshot after any kind of error, not only "selenium" error

**Comment by rdpanek** [comment]
This sounds good! When you see the possibility of implementation?

**Comment by jaroslav-kubicek** [comment]
My humble estimation is that I should have first draft by Sunday.

**Comment by jaroslav-kubicek** [comment]
Taking screenshots:

I've prepared functional proposal how it could work, see commit https://github.com/test-stack/webdriver/commit/1d51f34f0391b076d3760d8b07c27833fbb7276b

User of our tool have following ways how to affect behaviour:
- with cli option `--no-screenshots`, user can deny making screenshots at all
- with config setting `screenDir`, user can define directory in which screens should be saved, default is `./screenshots`

**Comment by rdpanek** [comment]
what's progress?

**Comment by rdpanek** [comment]
Done!
